[package]
name = "rsdbs"
version = "0.1.0"
edition = "2018"
description = "Efficient and compact bitsets for Rust."
license = "MIT"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false